export const kpis = [
  { label: "Properties for Sale", value: 684, change: 12.4, color: "var(--chart-1)", icon: "home" },
  { label: "Properties for Rent", value: 546, change: 8.1, color: "var(--chart-3)", icon: "key" },
  { label: "Total Customers", value: 5632, change: 23.5, color: "var(--chart-2)", icon: "users" },
  { label: "Total Cities", value: 90, change: 4.2, color: "var(--chart-4)", icon: "map" },
  { label: "Active Leads", value: 1284, change: 18.9, color: "var(--chart-5)", icon: "trending-up" },
  { label: "AI Conversations", value: 412, change: 31.2, color: "var(--chart-1)", icon: "bot" },
  { label: "Revenue (Mo)", value: 236535, change: 0.8, color: "var(--chart-2)", icon: "dollar-sign", prefix: "$" },
  { label: "Today's Visits", value: 3284, change: -2.4, color: "var(--chart-4)", icon: "eye" },
  { label: "Total Ad Leads", value: 180, change: 15.6, color: "var(--chart-1)", icon: "target" },
  { label: "Facebook Leads", value: 85, change: 12.4, color: "var(--chart-2)", icon: "facebook" },
  { label: "Instagram Leads", value: 65, change: 18.2, color: "var(--chart-3)", icon: "instagram" },
  { label: "Meta Leads", value: 30, change: 8.1, color: "var(--chart-4)", icon: "bot" },
];

export const revenueData = [
  { name: "Jan", last: 720, current: 380 },
  { name: "Feb", last: 540, current: 300 },
  { name: "Mar", last: 490, current: 320 },
  { name: "Apr", last: 380, current: 210 },
  { name: "May", last: 680, current: 520 },
  { name: "Jun", last: 700, current: 540 },
  { name: "Jul", last: 470, current: 260 },
  { name: "Aug", last: 590, current: 410 },
  { name: "Sep", last: 620, current: 480 },
];

import type { Property } from "@/types";

export const referrals = [
  { label: "Social Media", value: 64, color: "var(--chart-1)" },
  { label: "Marketplaces", value: 40, color: "var(--chart-2)" },
  { label: "Websites", value: 50, color: "var(--chart-3)" },
  { label: "Digital Ads", value: 80, color: "var(--chart-4)" },
  { label: "Others", value: 15, color: "var(--chart-5)" },
];

export const conversions = [
  { label: "Facebook Ad", value: 35, color: "var(--chart-1)", won: 7, total: 20 },
  { label: "Instagram Ad", value: 25, color: "var(--chart-2)", won: 5, total: 20 },
  { label: "Meta Ad", value: 40, color: "var(--chart-3)", won: 8, total: 20 },
  { label: "Website", value: 30, color: "var(--chart-4)", won: 15, total: 50 },
  { label: "Referral", value: 60, color: "var(--chart-5)", won: 30, total: 50 },
];

export const customerGrowth = [
  { name: "Mon", users: 320 },
  { name: "Tue", users: 480 },
  { name: "Wed", users: 410 },
  { name: "Thu", users: 620 },
  { name: "Fri", users: 720 },
  { name: "Sat", users: 580 },
  { name: "Sun", users: 690 },
];

export const propertyTypes = [
  { name: "Apartment", value: 420 },
  { name: "Villa", value: 180 },
  { name: "Office", value: 120 },
  { name: "Land", value: 90 },
  { name: "Studio", value: 64 },
];

export const properties: Property[] = [
  {
    id: "p1",
    title: "Metro Jayakar Apartment",
    description: "Stylish apartment with modern amenities.",
    price: 2250,
    city: "North Carolina",
    state: "USA",
    address: "230 Metro Lane",
    propertyType: "APARTMENT",
    bhk: 3,
    bathrooms: 2,
    area: "26M",
    amenities: ["Parking", "Gym"],
    images: [],
    status: "FOR_SALE",
    listedById: "mock-agent",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p2",
    title: "Letdo Ji Hotel & Apartment",
    description: "Well-positioned hotel apartment for businesses.",
    price: 2025,
    city: "Carolina North",
    state: "UK",
    address: "12 Letdo Street",
    propertyType: "HOTEL",
    bhk: 3,
    bathrooms: 2,
    area: "26M",
    amenities: ["Pool", "Concierge"],
    images: [],
    status: "FOR_RENT",
    listedById: "mock-agent",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p3",
    title: "Skyline Residency",
    description: "Luxury penthouse with skyline views.",
    price: 2925,
    city: "Manhattan",
    state: "USA",
    address: "58 Skyline Avenue",
    propertyType: "PENTHOUSE",
    bhk: 4,
    bathrooms: 3,
    area: "32M",
    amenities: ["Rooftop", "Gym"],
    images: [],
    status: "FOR_SALE",
    listedById: "mock-agent",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p4",
    title: "Taiwo Adewale Apartment",
    description: "Cozy, modern apartment with excellent views.",
    price: 1530,
    city: "Lagos",
    state: "Nigeria",
    address: "14 Adewale Road",
    propertyType: "APARTMENT",
    bhk: 3,
    bathrooms: 2,
    area: "26M",
    amenities: ["Parking", "Garden"],
    images: [],
    status: "FOR_RENT",
    listedById: "mock-agent",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p5",
    title: "Azure Bay Villa",
    description: "Spacious villa with waterfront access.",
    price: 4800,
    city: "Santorini",
    state: "Greece",
    address: "88 Azure Bay",
    propertyType: "VILLA",
    bhk: 5,
    bathrooms: 4,
    area: "48M",
    amenities: ["Pool", "Sea View"],
    images: [],
    status: "FOR_SALE",
    listedById: "mock-agent",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p6",
    title: "Downtown Loft 32",
    description: "Stylish loft in the heart of the city.",
    price: 1820,
    city: "Berlin",
    state: "Germany",
    address: "32 Downtown Street",
    propertyType: "LOFT",
    bhk: 2,
    bathrooms: 2,
    area: "18M",
    amenities: ["Open Plan", "City View"],
    images: [],
    status: "FOR_RENT",
    listedById: "mock-agent",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p7",
    title: "Olive Grove Estate",
    description: "Prestigious villa nestled in the countryside.",
    price: 3650,
    city: "Tuscany",
    state: "Italy",
    address: "17 Olive Grove",
    propertyType: "VILLA",
    bhk: 4,
    bathrooms: 3,
    area: "40M",
    amenities: ["Garden", "Wine Cellar"],
    images: [],
    status: "SOLD",
    listedById: "mock-agent",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p8",
    title: "Harbor View Penthouse",
    description: "High-end penthouse with harbor panoramas.",
    price: 5400,
    city: "Sydney",
    state: "Australia",
    address: "9 Harbor Road",
    propertyType: "PENTHOUSE",
    bhk: 4,
    bathrooms: 4,
    area: "52M",
    amenities: ["Terrace", "Gym"],
    images: [],
    status: "FOR_SALE",
    listedById: "mock-agent",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const topAgents = [
  { name: "Benny Chagur", role: "Top Agent", sales: 128, avatar: "BC" },
  { name: "Chynita Heree", role: "Senior Agent", sales: 96, avatar: "CH" },
  { name: "David Yers", role: "Agent", sales: 84, avatar: "DY" },
  { name: "Hawkins Maru", role: "Manager", sales: 72, avatar: "HM" },
];

export const revenueBreakdown = [
  { propertyId: "p1", title: "Metro Jayakar Apartment", address: "230 Metro Lane", income: 110000 },
  { propertyId: "p3", title: "Skyline Residency", address: "58 Skyline Avenue", income: 75000 },
  { propertyId: "p5", title: "Azure Bay Villa", address: "88 Azure Bay", income: 30000 },
  { propertyId: "p8", title: "Harbor View Penthouse", address: "9 Harbor Road", income: 21535 },
];
